MedProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from MedProject import settings
import main.views as main
from django.views.i18n import JavaScriptCatalog
from main.decorators import check_recaptcha
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_tools/', include('admin_tools.urls')),

    path('', main.index, name='index'),
    path('reviews/', main.ReviewsList.as_view(), name='reviews'),
    path('reviews/<int:page>/', main.ReviewsList.as_view(), name='reviews_page'),
    path('create_review/', check_recaptcha(main.create_review), name='create_review'),
    path('faq/', main.FaqView.as_view(), name='faq'),
    path('faq/<int:page>/', main.FaqView.as_view(), name='faq_page'),
    path('create_question/', check_recaptcha(main.create_question), name='create_question'),
    path('consultation/', main.consultation, name='consultation'),
    path('create_application/', check_recaptcha(main.create_application), name='create_application'),
    path('geography/', main.geography, name='geography'),
    path('news/', main.NewsList.as_view(), name='news'),
    path('news/<int:page>/', main.NewsList.as_view(), name='news_page'),
    path('single_news/<int:pk>/', main.single_news, name='single_news'),

    path('custom/', include('custom.urls', namespace='custom')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
    path('specialists/', include('specialists.urls', namespace='specialists')),

    path('editor/', include('django_summernote.urls')),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('password-reset/', PasswordResetView.as_view(template_name='authentication/password_reset.html'), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
import authentication.views as auth
from main.decorators import check_recaptcha

app_name = 'authentication'

urlpatterns = [
    path('login/', auth.login, name='login'),
    path('logout/', auth.logout, name='logout'),
    path('register/', auth.register, name='register'),
    path('edit_profile_page/', auth.edit_profile_page, name='edit_profile_page'),
    path('edit_profile/', check_recaptcha(auth.edit_profile), name='edit_profile'),
    path('edit_foas/', check_recaptcha(auth.edit_foas), name='edit_foas'),
    path('delete_application/', auth.delete_application, name='delete_application'),
    path('change_password/', auth.change_password, name='change_password'),
    path('verify/<str:email>/<str:key>/', auth.verify, name='verify'),
    path('send_verify_email_page/', auth.send_verify_email_page, name='send_verify_email_page'),
    path('renew_verification_key/', auth.renew_verification_key, name='renew_verification_key'),
    path('send_application/', auth.send_application, name='send_application'),
    path('rules/', auth.rules, name='rules'),
]

custom/urls.py
from django.urls import path
import custom.views as custom

app_name = 'custom'

urlpatterns = [
    path('add_album_page/', custom.add_album_page, name='add_album_page'),
    path('add_album/', custom.add_album, name='add_album'),
    path('add_fileset_page/', custom.add_fileset_page, name='add_fileset_page'),
    path('add_fileset/', custom.add_fileset, name='add_fileset'),
    path('<str:url>/', custom.constructor, name='constructor'),
]

specialists/urls.py
from django.urls import path
import specialists.views as spec
from main.decorators import check_recaptcha

app_name = 'specialists'

urlpatterns = [
    path('account/', spec.account, name='account'),
    path('create_article_page/', spec.create_article_page, name='create_article_page'),
    path('create_article/', check_recaptcha(spec.create_article), name='create_article'),
    path('edit_article_page/<int:pk>/', spec.edit_article_page, name='edit_article_page'),
    path('edit_article/', check_recaptcha(spec.edit_article), name='edit_article'),
    path('delete_article/', spec.delete_article, name='delete_article'),
    path('delete_application/', spec.delete_application, name='delete_application'),
    path('hide_article/', spec.hide_article, name='hide_article'),
    path('profile/<int:pk>/', spec.profile, name='profile'),
    path('article/<int:pk>/', spec.article, name='article'),
    path('specialists/', spec.SpecialistsList.as_view(), name='specialists'),
    path('specialists/<int:page>/', spec.SpecialistsList.as_view(), name='specialists_page'),
]

authentication/models.py
import os
import re
import shutil

from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from datetime import datetime, timedelta
import pytz
from django_summernote.models import Attachment
from PIL import Image, ImageOps
from MedProject.settings import BASE_DIR, BASE_URL
from django.conf import settings
from main.models import SiteContent
import calendar
import time
from uuid import uuid4


def compress_img(instance, field, directory, multiple=True, change_format=True):
    file = getattr(instance, field)
    img = Image.open(file)
    img = ImageOps.exif_transpose(img)
    current_gmt = time.gmtime()
    time_stamp = calendar.timegm(current_gmt)
    file_name = f'{time_stamp}-{uuid4().hex}.{"jpg" if change_format else file.name.split(".")[-1]}'
    new_file_path = os.path.join(BASE_DIR, 'media', directory, file_name)
    width = img.size[0]
    height = img.size[1]
    ratio = width / height
    if ratio > 1 and width > 1024:
        sizes = [1024, int(1024 / ratio)]
        img = img.resize(sizes)
    elif height > 1024:
        sizes = [int(1024 * ratio), 1024]
        img = img.resize(sizes)
    try:
        img.save(new_file_path, quality=90, optimize=True)
    except OSError:
        img = img.convert("RGB")
        img.save(new_file_path, quality=90, optimize=True)
    if multiple:
        try:
            shutil.rmtree(os.path.join(BASE_DIR, 'media', 'tmp'))
        except (FileNotFoundError, PermissionError):
            pass
        os.mkdir(os.path.join(BASE_DIR, 'media', 'tmp'))
    setattr(instance, field, os.path.join(directory, file_name))


def user_photo_upload(instance, filename):
    current_gmt = time.gmtime()
    time_stamp = calendar.timegm(current_gmt)
    file_name = f'{time_stamp}-{uuid4().hex}.jpg'
    new_file_path = os.path.join(BASE_DIR, 'media', 'profile_photos', file_name)
    return new_file_path


class FieldOfActivity(models.Model):

    name = models.CharField(max_length=64, verbose_name='Название')

    class Meta:
        verbose_name = 'Сфера деятельности'
        verbose_name_plural = 'Сферы деятельности'

    def __str__(self):
        return self.name


class User(AbstractUser):

    email = models.EmailField(unique=True, verbose_name='Email')
    first_name = models.CharField(max_length=64, verbose_name='Имя')
    patronymic = models.CharField(max_length=64, verbose_name='Отчество')
    last_name = models.CharField(max_length=64, verbose_name='Фамилия')
    # field_of_activity = models.ForeignKey(FieldOfActivity, on_delete=models.SET_NULL, null=True, verbose_name='Сфера деятельности')
    profession = models.CharField(max_length=64, verbose_name='Специализация')
    photo = models.ImageField(upload_to=user_photo_upload, verbose_name='Фото')
    city = models.CharField(max_length=128, verbose_name='Город')
    birthdate = models.DateField(null=True, verbose_name='Дата рождения')
    workplace_address = models.CharField(max_length=128, verbose_name='Адрес места работы')
    workplace_name = models.CharField(max_length=128, verbose_name='Название места работы')
    phone_number = models.CharField(max_length=16, verbose_name='Номер рабочего телефона')
    description = models.TextField(verbose_name='О себе')
    registered = models.BooleanField(default=False, verbose_name='Реестровый специалист')
    approved = models.BooleanField(default=False, verbose_name='Одобрен')
    email_verified = models.BooleanField(default=True, verbose_name='Почта подтверждена')
    verification_key = models.CharField(max_length=128, blank=True, null=True, verbose_name='Ключ подтверждения почты')
    verification_key_expires = models.DateTimeField(blank=True, null=True, verbose_name='Ключ истекает')
    order = models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок вывода')

    class Meta:
        verbose_name = 'Специалист ранней помощи'
        verbose_name_plural = 'Специалисты ранней помощи'

    @property
    def get_articles_count(self):
        return len(self.articles.select_related().filter(approved=True))

    @property
    def get_articles(self):
        return self.articles.select_related().filter(approved=True).order_by('-pk')

    @property
    def get_open_articles(self):
        return self.articles.select_related().filter(approved=True, hidden=False).order_by('-pk')

    @property
    def get_applications(self):
        return self.approval_applications.select_related().order_by('-pk')

    @property
    def get_waiting_edits(self):
        return self.edit_applications.select_related().filter(treated=False).order_by('-pk')

    @property
    def get_rejected_edits(self):
        return self.edit_applications.select_related().filter(treated=True, response=False).order_by('-pk')

    @property
    def get_birthdate(self):
        return self.birthdate.strftime("%d-%m-%Y")

    @property
    def application_exists(self):
        return UserApprovalApplication.objects.filter(user__pk=self.pk, treated=False).exists()

    @property
    def is_verification_key_expired(self):
        if datetime.now(pytz.timezone(settings.TIME_ZONE)) > self.verification_key_expires + timedelta(hours=48):
            return True
        return False

    @property
    def fields_of_activity(self):
        fields = self.fields.select_related()
        return ', '.join([str(field) for field in fields])

    @property
    def fields_of_activity_list(self):
        return self.fields.select_related()

    def __str__(self):
        try:
            return f'{self.last_name} {str(self.first_name)[0]}. {str(self.patronymic)[0]}.'
        except IndexError:
            return self.username


class FoAUserConnection(models.Model):

    foa = models.ForeignKey(FieldOfActivity, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Сфера деятельности')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='fields', verbose_name='Пользователь')

    class Meta:
        verbose_name = 'Сфера деятельности пользователей'
        verbose_name_plural = 'Сферы деятельности пользователей'

    def __str__(self):
        return str(self.foa)


class UserApprovalApplication(models.Model):

    user = models.ForeignKey(User, related_name='approval_applications', on_delete=models.CASCADE, verbose_name='Специалист')
    time = models.DateTimeField(auto_now=True, verbose_name='Время создания')
    treated = models.BooleanField(default=False, verbose_name='Обработана')
    response = models.BooleanField(default=False, verbose_name='Одобрить')
    comment = models.TextField(blank=True, null=True, verbose_name='Комментарий')

    class Meta:
        verbose_name = 'Заявка на одобрение профиля'
        verbose_name_plural = 'Заявки на одобрение профиля'

    def __str__(self):
        return f'{self.user}'


class UserEditApplication(models.Model):

    user = models.ForeignKey(User, related_name='edit_applications', on_delete=models.CASCADE, verbose_name='Специалист')
    field = models.CharField(max_length=32, verbose_name='Поле')
    verbose_field = models.CharField(max_length=32, null=True, verbose_name='Поле')
    old_value = models.TextField(verbose_name='Старое значение')
    new_value = models.TextField(verbose_name='Новое значение')
    time = models.DateTimeField(auto_now=True, verbose_name='Время создания')
    treated = models.BooleanField(default=False, verbose_name='Обработана')
    response = models.BooleanField(default=False, verbose_name='Одобрить')
    comment = models.TextField(blank=True, null=True, verbose_name='Комментарий')

    class Meta:
        verbose_name = 'Заявка на изменение профиля'
        verbose_name_plural = 'Заявки на изменение профиля'

    def __str__(self):
        return f'{self.user} - {self.field}'

    @property
    def get_value(self):
        if self.field == 'field_of_activity':
            result = re.sub(r'id:[0-9]+\|', '', str(self.new_value))
            result = re.sub(r'\|', ', ', result)
            return result[:-2]
        else:
            return self.new_value


@receiver(models.signals.pre_save, sender=User)
def compress_user_photo(sender, instance, raw, using, update_fields, *args, **kwargs):
    if not instance.pk:
        compress_img(instance, 'photo', 'profile_photos')


@receiver(models.signals.pre_save, sender=UserApprovalApplication)
def approve_user(sender, instance, raw, using, update_fields, *args, **kwargs):
    if instance.response:
        instance.user.approved = True
        instance.user.approved_at = datetime.now()
        instance.user.save()
        if not BASE_URL == 'http://127.0.0.1:8000':
            message = f'{SiteContent.objects.get(name="email_approved_text").content}'
            send_mail(
                'Ваш профиль одобрен',
                message,
                settings.EMAIL_HOST_USER,
                [instance.user.email],
                fail_silently=False
            )
    if instance.response or instance.comment:
        instance.treated = True


@receiver(models.signals.pre_save, sender=UserEditApplication)
def approve_edit(sender, instance, raw, using, update_fields, *args, **kwargs):
    if instance.response:
        if instance.field == 'field_of_activity':
            FoAUserConnection.objects.filter(user__pk=instance.user.pk).delete()
            for value in re.findall(r'id:[0-9]+\|', instance.new_value):
                new_value = int(value[3:-1])
                try:
                    foa = FieldOfActivity.objects.get(pk=new_value)
                    FoAUserConnection.objects.create(foa=foa, user=instance.user)
                except ObjectDoesNotExist:
                    pass
        elif instance.field == 'photo':
            try:
                os.remove(os.path.join(BASE_DIR, 'media', instance.user.photo.name))
            except (FileNotFoundError, UnicodeEncodeError):
                pass

authentication/templates/authentication/change_password.html
{% extends 'main/base.html' %}
{% load static %}
{% block js %}
<script src="{% static 'js/login.js' %}"></script>
{% endblock %}
{% block menu %}
<a href="{% url 'index' %}" class="menu-page">Вернуться на сайт</a>
<a href="{% url 'specialists:account' %}" class="menu-page">Личный кабинет</a>
<a href="{% url 'authentication:edit_profile_page' %}" class="menu-page">Редактировать профиль</a>
<a href="{% url 'authentication:logout' %}" class="menu-page">Выйти</a>
{% endblock %}
{% block content %}
<h1 class="page-title">Смена пароля</h1>
<div class="separator"></div>
<form action="{% url 'authentication:change_password' %}" class="consultation-form change-password-form" method="post">
    <div class="consultation-form-subblock">
        {% csrf_token %}
        {% for field in form %}
            {{ field }}
        {% endfor %}
        <input type="submit" class="med-button login-submit" value="Поменять">
        <a href="{% url 'authentication:edit_profile_page' %}" class="consultation-read-link">Назад</a>
    </div>
</form>
<div class="register-errors-block">
    {% for field in form %}
        {{ field.errors }}
    {% endfor %}
</div>
{% endblock %}

authentication/templates/authentication/login.html
{% extends 'main/base.html' %}
{% load static %}
{% block js %}
<script src="{% static 'js/login.js' %}"></script>
{% endblock %}
{% block content %}
<h1 class="page-title">Авторизация</h1>
<div class="separator"></div>
<p class="consultation-intro">{{ text|safe }}</p>
<form action="{% url 'authentication:login' %}" class="consultation-form login-form" method="post">
    <div class="consultation-form-subblock">
        <img src="{% static 'img/password_show.svg' %}" alt="show" class="login-password-show">
        <img src="{% static 'img/password_hide.svg' %}" alt="show" class="login-password-hide">
        {% csrf_token %}
        {% for field in login_form %}
            {{ field }}
        {% endfor %}
        <input type="submit" class="med-button login-submit" value="Войти">
        <a href="{% url 'authentication:register' %}" class="consultation-read-link" style="margin-bottom: 5px;">Зарегистрироваться</a>
        <a href="{% url 'password_reset' %}" class="consultation-read-link">Забыли пароль?</a>
    </div>
</form>
{% endblock %}

authentication/templates/authentication/notification.html
{% extends 'main/base.html' %}
{% load static %}
{% block menu %}
<a href="{% url 'index' %}" class="menu-page">Вернуться на сайт</a>
<a href="{% url 'specialists:account' %}" class="menu-page">Личный кабинет</a>
<a href="{% url 'authentication:edit_profile_page' %}" class="menu-page">Редактировать профиль</a>
<a href="{% url 'authentication:logout' %}" class="menu-page">Выйти</a>
{% endblock %}
{% block content %}
<h1 class="faq-form-notification">{{ notification }}</h1>
{% endblock %}

authentication/templates/authentication/password_reset.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<h2 class="page-title">Сброс пароля</h2>
<div class="separator"></div>
<form method="post" class="reset-password-form">
    {% csrf_token %}
    {% for field in form %}
            {{ field.label_tag }} 
            {{ field }}
            {% if field.errors %}
                <small>{{ field.errors|striptags  }}</small> 
            {% endif %}
    {% endfor %}
    <input type="submit" value="Отправить" class="med-button">
    <a href="{%url 'authentication:login' %}"  class="consultation-read-link">Отмена</a>
</form>
{% endblock %}

authentication/templates/authentication/password_reset_complete.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<h1 class="faq-form-notification">Ваш пароль был успешно изменён. <a href="{% url 'authentication:login' %}" class="consultation-read-link">Нажмите, чтобы войти.</a></h1>
{% endblock %}

authentication/templates/authentication/password_reset_confirm.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<h2 class="page-title">Смена пароля</h2>
<div class="separator"></div>
<form method="post" class="reset-password-form">
    {% csrf_token %}
    {% for field in form %}
        {{ field.label_tag }} 
        {{ field }}
        {% if field.errors %}
            <small>{{ field.errors|striptags  }}</small> 
        {% endif %}
    {% endfor %}
    <button type="submit" class="med-button">Сменить пароль</button>
</form>
{% endblock %}

authentication/templates/authentication/password_reset_done.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<div class="faq-form-notification">Письмо со ссылкой для сброса пароля было выслано на указанный адрес электронной почты!</div>
{% endblock %}

authentication/templates/authentication/register.html
{% extends 'main/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'css/summernote.min.css'%}">
<style>
    html, body {
        font-size: 16px;
        line-height: 1;
        font-family: serif;
    }

    a:hover {
        text-decoration: none;
    }

    h1, h2, h3 {
        font-weight: bolder;
        margin: 0;
    }
    
    #id_description {
        display: none;
    }

    .faq-form-block {
        width: auto !important;
    }

    @media (max-width: 400px) {
        .faq-form-block {
            width: 100% !important;
            padding: 1.5rem 10px !important;
            box-sizing: border-box;
        }

        .edit-profile-photo-block {
            width: calc(100% - 20px) !important;
        }
    }
</style>
{% endblock %}
{% block js %}
<link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/croppie.css' %}" />
<script src="{% static 'js/croppie.js' %}"></script>
<script src="{% static 'js/register.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/summernote.min.js' %}"></script>
<script src="{% static 'js/summernote-ru-RU.min.js' %}"></script>
{% endblock %}
{% block content %}
<h1 class="page-title">Регистрация</h1>
<div class="separator"></div>
<p class="consultation-intro">{{ text|safe }}</p>
<form action="{% url 'authentication:register' %}" class="consultation-form register-form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="consultation-form-subblock">
        {% for field in first_block %}
            {{ field }}
        {% endfor %}
    </div>
    <div class="consultation-form-subblock">
        <div class="med-input register-fake-select" id="register-fake-select">
            <img src="{% static 'img/menu-arrow.svg' %}" alt="+" class="register-fake-select-arrow">
            <div class="register-selected">Сферы деятельности в ранней помощи</div>
            <div class="register-options-block"></div>
        </div>
        {% for field in second_block %}
            {{ field }}
            {% if field.name == 'photo' %}
            <label for="id_photo" class="med-input register-photo-label">Фото профиля</label>
            {% endif %}
        {% endfor %}
    </div>
    <div class="consultation-form-subblock">
        <div class="summernote"></div>
        {% for field in third_block %}
            {{ field }}
        {% endfor %}
        <div class="consultation-checkbox-block"><input type="checkbox" class="consultation-checkbox"><span>Даю согласие на обработку персональных данных</span></div>
        <a {% if rules_url %}href="{% url 'custom:constructor' url=rules_url %}"{% else %}href="#"{% endif %} class="consultation-read-link">Правила обработки персональных данных</a>
        <input type="submit" class="med-button register-submit" value="Зарегистрироваться">
        <a href="{% url 'authentication:login' %}" class="consultation-read-link">Войти</a>
    </div>
</form>
<div class="register-errors-block">
    {% for field in first_block %}
        {{ field.errors }}
    {% endfor %}
    {% for field in second_block %}
        {{ field.errors }}
    {% endfor %}
    {% for field in third_block %}
        {{ field.errors }}
    {% endfor %}
</div>
<div class="faq-background">
    <div class="faq-form-block">
        <div class="edit-profile-photo-block">
            <div class="edit-profile-photo"></div>
        </div>
        <div class="med-button edit-profile-photo-save">Сохранить</div>
    </div>
</div>
{% endblock %}

authentication/templates/authentication/rules.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<h1 class="page-title">Правила обработки персональных данных</h1>
<div class="separator"></div>
<p class="consultation-intro">{{ text|safe }}</p>
{% endblock %}