MedProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from MedProject import settings
import main.views as main
from django.views.i18n import JavaScriptCatalog
from main.decorators import check_recaptcha
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_tools/', include('admin_tools.urls')),

    path('', main.index, name='index'),
    path('reviews/', main.ReviewsList.as_view(), name='reviews'),
    path('reviews/<int:page>/', main.ReviewsList.as_view(), name='reviews_page'),
    path('create_review/', check_recaptcha(main.create_review), name='create_review'),
    path('faq/', main.FaqView.as_view(), name='faq'),
    path('faq/<int:page>/', main.FaqView.as_view(), name='faq_page'),
    path('create_question/', check_recaptcha(main.create_question), name='create_question'),
    path('consultation/', main.consultation, name='consultation'),
    path('create_application/', check_recaptcha(main.create_application), name='create_application'),
    path('geography/', main.geography, name='geography'),
    path('news/', main.NewsList.as_view(), name='news'),
    path('news/<int:page>/', main.NewsList.as_view(), name='news_page'),
    path('single_news/<int:pk>/', main.single_news, name='single_news'),

    path('custom/', include('custom.urls', namespace='custom')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
    path('specialists/', include('specialists.urls', namespace='specialists')),

    path('editor/', include('django_summernote.urls')),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('password-reset/', PasswordResetView.as_view(template_name='authentication/password_reset.html'), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
import authentication.views as auth
from main.decorators import check_recaptcha

app_name = 'authentication'

urlpatterns = [
    path('login/', auth.login, name='login'),
    path('logout/', auth.logout, name='logout'),
    path('register/', auth.register, name='register'),
    path('edit_profile_page/', auth.edit_profile_page, name='edit_profile_page'),
    path('edit_profile/', check_recaptcha(auth.edit_profile), name='edit_profile'),
    path('edit_foas/', check_recaptcha(auth.edit_foas), name='edit_foas'),
    path('delete_application/', auth.delete_application, name='delete_application'),
    path('change_password/', auth.change_password, name='change_password'),
    path('verify/<str:email>/<str:key>/', auth.verify, name='verify'),
    path('send_verify_email_page/', auth.send_verify_email_page, name='send_verify_email_page'),
    path('renew_verification_key/', auth.renew_verification_key, name='renew_verification_key'),
    path('send_application/', auth.send_application, name='send_application'),
    path('rules/', auth.rules, name='rules'),
]

custom/urls.py
from django.urls import path
import custom.views as custom

app_name = 'custom'

urlpatterns = [
    path('add_album_page/', custom.add_album_page, name='add_album_page'),
    path('add_album/', custom.add_album, name='add_album'),
    path('add_fileset_page/', custom.add_fileset_page, name='add_fileset_page'),
    path('add_fileset/', custom.add_fileset, name='add_fileset'),
    path('<str:url>/', custom.constructor, name='constructor'),
]

specialists/urls.py
from django.urls import path
import specialists.views as spec
from main.decorators import check_recaptcha

app_name = 'specialists'

urlpatterns = [
    path('account/', spec.account, name='account'),
    path('create_article_page/', spec.create_article_page, name='create_article_page'),
    path('create_article/', check_recaptcha(spec.create_article), name='create_article'),
    path('edit_article_page/<int:pk>/', spec.edit_article_page, name='edit_article_page'),
    path('edit_article/', check_recaptcha(spec.edit_article), name='edit_article'),
    path('delete_article/', spec.delete_article, name='delete_article'),
    path('delete_application/', spec.delete_application, name='delete_application'),
    path('hide_article/', spec.hide_article, name='hide_article'),
    path('profile/<int:pk>/', spec.profile, name='profile'),
    path('article/<int:pk>/', spec.article, name='article'),
    path('specialists/', spec.SpecialistsList.as_view(), name='specialists'),
    path('specialists/<int:page>/', spec.SpecialistsList.as_view(), name='specialists_page'),
]

specialists/models.py
from django.db import models
import os
from datetime import datetime
from django.dispatch import receiver

from MedProject.settings import BASE_DIR
from authentication.models import User


class Article(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name='Автор', related_name='articles')
    hidden = models.BooleanField(default=False, verbose_name='Статья скрыта')
    theme = models.TextField(verbose_name='Тематика')
    title = models.TextField(verbose_name='Название статьи')
    text = models.TextField(verbose_name='Текст статьи')
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата написания')
    approved_at = models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')
    approved = models.BooleanField(default=False, verbose_name='Одобрено')

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return self.title

    @property
    def get_files(self):
        return self.files.select_related()


class ArticleFile(models.Model):

    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='files')
    file = models.FileField(upload_to='documents/')
    name = models.CharField(max_length=128, null=True, blank=True, verbose_name='Название (необязательно)')

    class Meta:
        verbose_name = 'Файл из статьи'
        verbose_name_plural = 'Файлы из статей'

    @property
    def extension(self):
        name, ext = os.path.splitext(self.file.name)
        return ext


class ArticleApprovalApplication(models.Model):

    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='Статья')
    time = models.DateTimeField(auto_now=True, verbose_name='Время создания')
    treated = models.BooleanField(default=False, verbose_name='Обработана')
    response = models.BooleanField(default=False, verbose_name='Опубликовать')
    comment = models.TextField(blank=True, null=True, verbose_name='Комментарий')

    class Meta:
        verbose_name = 'Заявка на публикацию статьи'
        verbose_name_plural = 'Заявки на публикацию статьи'

    def __str__(self):
        return f'{self.article}'


@receiver(models.signals.pre_save, sender=ArticleApprovalApplication)
def approve_article(sender, instance, raw, using, update_fields, *args, **kwargs):
    if instance.response:
        instance.article.approved = True
        instance.article.approved_at = datetime.now()
        instance.article.save()
    if instance.response or instance.comment:
        instance.treated = True


@receiver(models.signals.pre_delete, sender=ArticleFile)
def delete_file(sender, instance, using, origin, **kwargs):
    try:
        os.remove(os.path.join(BASE_DIR, 'media', instance.file.name))
    except (FileNotFoundError, UnicodeEncodeError):
        pass

specialists/views.py
import calendar
import time
from uuid import uuid4

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import ListView
from authentication.models import User
from main.models import SiteContent
from .models import Article, ArticleFile, ArticleApprovalApplication
from custom.models import Section, Page


@login_required
def account(request):

    not_treated = ArticleApprovalApplication.objects.filter(article__author__pk=request.user.pk, treated=False)
    rejected = ArticleApprovalApplication.objects.filter(article__author__pk=request.user.pk, treated=True, response=False)

    context = {
        'title': 'Личный кабинет',
        'not_treated': not_treated,
        'rejected': rejected,
        'header_content': [SiteContent.objects.get(name='email').content,
                                     SiteContent.objects.get(name='phone').content,
                                     SiteContent.objects.get(name='phone').content.translate(
                                         str.maketrans({' ': '', '-': '', '(': '', ')': ''}))],
    }

    return render(request, 'specialists/account.html', context)


def profile(request, pk):

    specialist = User.objects.get(pk=pk)

    context = {
        'title': f'{specialist}',
        'specialist': specialist,
        'menu_sections': Section.objects.all().order_by('order'),
        'account_section_id': int(SiteContent.objects.get(name='account_section_id').content),
        'menu_pages': Page.objects.filter(section=None),
        'header_content': [SiteContent.objects.get(name='email').content,
                                     SiteContent.objects.get(name='phone').content,
                                     SiteContent.objects.get(name='phone').content.translate(
                                         str.maketrans({' ': '', '-': '', '(': '', ')': ''}))]
    }

    return render(request, 'specialists/profile.html', context)


def article(request, pk):

    art = Article.objects.get(pk=pk)

    context = {
        'title': f'{art}',
        'article': art,
        'files': len(art.get_files) > 0,
        'menu_sections': Section.objects.all().order_by('order'),
        'account_section_id': int(SiteContent.objects.get(name='account_section_id').content),
        'menu_pages': Page.objects.filter(section=None),
        'header_content': [SiteContent.objects.get(name='email').content,
                                     SiteContent.objects.get(name='phone').content,
                                     SiteContent.objects.get(name='phone').content.translate(
                                         str.maketrans({' ': '', '-': '', '(': '', ')': ''}))]
    }

    return render(request, 'specialists/article.html', context)


class SpecialistsList(ListView):
    model = User
    template_name = 'specialists/specialists.html'
    paginate_by = 12

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Специалисты ранней помощи',
        context['menu_sections'] = Section.objects.all().order_by('order')
        context['account_section_id'] = int(SiteContent.objects.get(name='account_section_id').content)
        context['menu_pages'] = Page.objects.filter(section=None)
        context['header_content'] = [SiteContent.objects.get(name='email').content,
                                     SiteContent.objects.get(name='phone').content,
                                     SiteContent.objects.get(name='phone').content.translate(
                                         str.maketrans({' ': '', '-': '', '(': '', ')': ''}))]

        return context

    def get_queryset(self):
        return User.objects.filter(is_superuser=False, approved=True).order_by('order')


@login_required
def create_article_page(request):

    context = {
        'title': 'Новый материал',
        'header_content': [SiteContent.objects.get(name='phone').content, SiteContent.objects.get(name='email').content]
    }

    return render(request, 'specialists/create_article_page.html', context)


@login_required
def create_article(request):
    theme = request.POST.get('theme')
    title = request.POST.get('title')
    text = request.POST.get('text')

    if request.recaptcha_is_valid:
        if theme and title and text:
            try:
                art = Article.objects.create(author=request.user, theme=theme, title=title, text=text)
                ArticleApprovalApplication.objects.create(article=art)
                for pk_name, file in request.FILES.items():
                    name = pk_name[pk_name.index('-') + 1:]
                    current_gmt = time.gmtime()
                    time_stamp = calendar.timegm(current_gmt)
                    file.name = f'{time_stamp}-{uuid4().hex}.{file.name.split(".")[-1]}'
                    ArticleFile.objects.create(file=file, article=art, name=name)
                return JsonResponse({'result': 'ok'})
            except:
                pass
    else:
        return JsonResponse({'result': 'captcha'})

    return JsonResponse({'result': 'failed'})


@login_required
def edit_article_page(request, pk):

    art = Article.objects.get(pk=pk)

    context = {
        'title': 'Редактирование материала',
        'article': art if not art.approved else None,
        'header_content': [SiteContent.objects.get(name='email').content,
                                     SiteContent.objects.get(name='phone').content,
                                     SiteContent.objects.get(name='phone').content.translate(
                                         str.maketrans({' ': '', '-': '', '(': '', ')': ''}))],
        'files_quantity': len(art.get_files)
    }

    return render(request, 'specialists/edit_article_page.html', context)


@login_required
def edit_article(request):

    pk = int(request.POST.get('pk'))
    theme = request.POST.get('theme')
    title = request.POST.get('title')
    text = request.POST.get('text')
    kept_files = [int(i) for i in request.POST.get('kept_files').split(',') if i] if request.POST.get('kept_files') else []

    if request.recaptcha_is_valid:
        art = Article.objects.get(pk=pk)
        if not art.approved:
            try:
                art.theme = theme
                art.title = title
                art.text = text
                art.save()
                current_files = art.get_files
                for file in current_files:
                    if file.pk not in kept_files:
                        ArticleFile.objects.get(pk=file.pk).delete()
                for pk_name, file in request.FILES.items():
                    name = pk_name[pk_name.index('-') + 1:]
                    current_gmt = time.gmtime()
                    time_stamp = calendar.timegm(current_gmt)
                    file.name = f'{time_stamp}-{uuid4().hex}.{file.name.split(".")[-1]}'
                    ArticleFile.objects.create(file=file, article=art, name=name)
                return JsonResponse({'result': 'ok'})
            except:
                pass
    else:
        return JsonResponse({'result': 'captcha'})

    return JsonResponse({'result': 'failed'})


@login_required
def delete_article(request):
    pk = int(request.POST.get('pk'))
    Article.objects.get(pk=pk).delete()
    return JsonResponse({'result': 'ok'})


@login_required
def delete_application(request):
    pk = int(request.POST.get('pk'))
    ArticleApprovalApplication.objects.get(pk=pk).article.delete()
    return JsonResponse({'result': 'ok'})


@login_required
def hide_article(request):
    pk = int(request.POST.get('pk'))
    art = Article.objects.get(pk=pk)
    art.hidden = not art.hidden
    art.save()
    return JsonResponse({'result': 'ok'})

specialists/templates/specialists/account.html
{% extends 'main/base.html' %}
{% load static %}
{% block js %}
<script src="{% static 'js/text-adjust.js' %}"></script>
<script src="{% static 'js/account.js' %}"></script>
{% endblock %}
{% block menu %}
<a href="{% url 'index' %}" class="menu-page">Вернуться на сайт</a>
<a href="{% url 'authentication:edit_profile_page' %}" class="menu-page">Редактировать профиль</a>
<a href="{% url 'authentication:logout' %}" class="menu-page">Выйти</a>
{% endblock %}
{% block content %}
<h3 class="page-title">Личный кабинет</h3>
<div class="separator"></div>
{% if not user.email_verified %}
    <div class="account-email-verification-block">
    {% if not user.is_verification_key_expired %}
        Ваш адрес электронной почты не подтверждён. Письмо со ссылкой для подтверждения уже было отправлено на указанный вами адрес. 
        <a href="{% url 'authentication:send_verify_email_page' %}" class="consultation-read-link">Нажмите, чтобы отправить письмо повторно.</a>
    {% else %}
        Ваш адрес электронной почты не подтверждён. Ключ подтверждения истёк. 
        <a href="{% url 'authentication:renew_verification_key' %}" class="consultation-read-link">Нажмите, чтобы обновить ключ и отправить письмо со ссылкой для подтверждения на ваш адрес электронной почты.</a>
    {% endif %}
    </div>
{% endif %}
{% if user.approved %}
    {% csrf_token %}
    <div class="account-dashboard">
        <div class="specialists-info">
            <span class="specialists-info-label">Статей опубликовано: </span>{{ user.get_articles_count }}
        </div>
        <a href="{% url 'specialists:create_article_page' %}" class="med-button mini-med-button account-button">Разместить новый материал</a>
    </div>
    <div class="separator"></div>
    <div class="profile-title">Материалы на рассмотрении</div>
    <div class="account-block">
        {% for application in not_treated %}
        <div class="account-application-block" id="application-{{ application.pk }}">
            <div class="account-application-content">
                <span class="account-application-title text-to-adjust" id="tta-title-{{ application.pk }}">{{ application.article.title }}</span>
                <span class="account-application-text text-to-adjust" id="tta-text-{{ application.pk }}">{{ application.article.text }}</span>
                {% if application.article.get_files %}
                    <div class="account-application-files">
                        {% for file in application.article.get_files %}
                            <div class="account-application-file-block">
                                <a href="/media/{{ file.file }}" class="account-application-file">{{ file.extension }}</a>
                                <span class="account-application-file-name">{% if file.name %}{{ file.name }}{% endif %}</span>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="account-application-options">
                <div class="index-news-date profile-article-date">Отправлено: {{ application.article.created_at }}</div>
                <div class="account-application-buttons">
                    <a href="{% url 'specialists:edit_article_page' application.article.pk %}" class="med-button mini-med-button">Редактировать</a>
                    <span class="med-button account-delete-article mini-med-button" id="delete-{{ application.pk }}">Удалить статью</span>
                </div>
            </div>
        </div>
        {% endfor %}
        {% if not not_treated %}
            <div class="account-block-none">Нет материалов в этой категории</div>
        {% endif %}
    </div>
    <div class="separator"></div>
    <div class="profile-title">Отклонено</div>
    <div class="account-block">
        {% for application in rejected %}
        <div class="account-application-block" id="application-{{ application.pk }}">
            <div class="account-application-content">
                <span class="account-application-title text-to-adjust" id="tta-title-{{ application.pk }}">{{ application.article.title }}</span>
                <span class="account-application-text text-to-adjust" id="tta-text-{{ application.pk }}">{{ application.article.text }}</span>
                {% if application.article.get_files %}
                    <div class="account-application-files">
                        {% for file in application.article.get_files %}
                            <div class="account-application-file-block">
                                <a href="/media/{{ file.file }}" class="account-application-file">{{ file.extension }}</a>
                                <span class="account-application-file-name">{% if file.name %}{{ file.name }}{% endif %}</span>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="account-application-options">
                <div class="index-news-date profile-article-date">Отправлено: {{ application.article.created_at }}</div>
                <div class="account-application-buttons">
                    <a href="{% url 'specialists:edit_article_page' application.article.pk %}" class="med-button mini-med-button">Редактировать</a>
                    <span class="med-button account-delete-application mini-med-button" id="delete-{{ application.pk }}">Удалить статью</span>
                </div>
                <div class="account-application-comment">Комментарий: {{ application.comment }}</div>
            </div>
        </div>
        {% endfor %}
        {% if not rejected %}
            <div class="account-block-none">Нет материалов в этой категории</div>
        {% endif %}
    </div>
    <div class="separator"></div>
    <div class="profile-title">История публикаций</div>
    <div class="profile-articles-block">
        {% for article in user.get_articles %}
            <div class="profile-article-block" id="article-{{ article.pk }}">
                <div class="profile-article-vertical-line"></div>
                <div class="profile-article-icon-block">
                    <img src="{% static 'img/article.png' %}" class="profile-article-icon">
                </div>
                <div class="account-article-content{% if article.hidden %} account-hidden{% endif %}">
                    <div class="profile-article-content">
                        <a href="{% url 'specialists:article' article.pk %}" class="index-link profile-article-title" id="tta-text-article-{{ article.pk }}">{{ article.title }}</a>
                        <div class="index-news-date profile-article-date">{{ article.approved_at }}</div>
                    </div>
                    <div class="account-application-buttons">
                        <span class="med-button account-hide-article mini-med-button" id="hide-{{ article.pk }}">
                            {% if article.hidden %}Сделать видимой{% else %}Скрыть статью{% endif %}
                        </span>
                        <span class="med-button account-delete-article mini-med-button" id="delete-article-{{ article.pk }}">Удалить статью</span>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if not user.get_articles %}
            <div class="account-block-none">Нет материалов в этой категории</div>
        {% endif %}
    </div>
    <div class="faq-background">
        <div class="faq-form-block">
            <span class="faq-form-notification">Вы точно хотите удалить этот материал?</span>
            <div class="account-delete-buttons">
                <span class="med-button account-delete-confirm">Да</span>
                <span class="med-button account-delete-cancel">Нет</span>
            </div>
        </div>
    </div>
{% else %}
    <div class="profile-title">История заявок на одобрение профиля</div>
    <div class="profile-articles-block">
        {% for application in user.get_applications %}
            <div class="profile-article-block">
                <div class="profile-article-vertical-line"></div>
                <div class="profile-article-icon-block">
                    <img src="{% static 'img/application.png' %}" class="profile-article-icon">
                </div>
                <div class="profile-article-content">
                    <div class="index-news-date profile-article-date">Отправлено: {{ application.time }}</div>
                    <div class="index-news-date profile-article-date">Статус: 
                        {% if application.treated and not application.response %}
                            Отклонено</div> 
                            <div class="account-application-comment">Комментарий: {{ application.comment }}</div>
                        {% else %}
                            На рассмотрении</div>
                        {% endif %}
                    </div>
            </div>
        {% endfor %}
    </div>
    <a href="{% url 'authentication:edit_profile_page' %}" class="med-button mini-med-button" style="display: block; width: 250px; margin-top: 20px;">Редактировать профиль</a>
    {% if not user.application_exists %}
        <a href="{% url 'authentication:send_application' %}" class="med-button mini-med-button" style="display: block; width: 250px; margin-top: 20px;">Отправить заявку</a>
    {% endif %}
{% endif %}
{% endblock %}

specialists/templates/specialists/create_article_page.html
{% extends 'main/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'css/summernote.min.css'%}">
<style>
    html, body {
        font-size: 16px;
        line-height: 1;
        font-family: serif;
    }

    a:hover {
        text-decoration: none;
    }

    h1, h2, h3 {
        font-weight: bolder;
        margin: 0;
    }
</style>
{% endblock %}
{% block js %}
<script src='https://www.google.com/recaptcha/api.js'></script>
<script src="{% static 'js/create_article.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/summernote.min.js' %}"></script>
<script src="{% static 'js/summernote-ru-RU.min.js' %}"></script>
{% endblock %}
{% block menu %}
<a href="{% url 'index' %}" class="menu-page">Вернуться на сайт</a>
<a href="{% url 'specialists:account' %}" class="menu-page">Личный кабинет</a>
<a href="{% url 'authentication:edit_profile_page' %}" class="menu-page">Редактировать профиль</a>
<a href="{% url 'authentication:logout' %}" class="menu-page">Выйти</a>
{% endblock %}
{% block content %}
<h3 class="page-title">Новый материал</h3>
<div class="separator"></div>
<div class="create-article-form">
    <input type="text" class="med-input create-article-theme" placeholder="Тема">
    <input type="text" class="med-input create-article-title" placeholder="Название">
    <!-- <textarea class="med-input create-article-text" placeholder="Текст статьи"></textarea> -->
    <div class="summernote"></div>
</div>
<div class="separator"></div>
<h3 class="page-label">Прикрепить файлы</h3>
<div class="create-article-files">
    <div class="create-article-file-block">
        <input type="text" class="med-input create-article-file-name" placeholder="Подпись к файлу" id="name-0">
        <input type="file" class="med-input create-article-file" id="file-0">
        <div class="create-article-remove-file">+</div>
    </div>
    <div class="create-article-add-file">+</div>
</div>
<div class="separator"></div>
{% csrf_token %}
<div class="create-article-recaptha-wrapper"><div class="form-group g-recaptcha" data-sitekey="6Lf_F2YoAAAAAAVQNp1zYPQk7S5cdxh7ylOkxGCU"></div></div>
<div class="create-article-notification faq-form-notification"></div>
<div class="med-button create-article-submit">Отправить</div>
<div class="faq-background">
    <div class="faq-form-block">
        <span class="faq-form-notification">Материал успешно отправлен на проверку!</span>
        <a href="{% url 'specialists:account' %}" class="med-button" style="margin-top: 10px;">Ок</a>
    </div>
</div>
{% endblock %}

specialists/templates/specialists/edit_article_page.html
{% extends 'main/base.html' %}
{% load static %}
{% load tags %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static 'css/summernote.min.css'%}">
<style>
    html, body {
        font-size: 16px;
        line-height: 1;
        font-family: serif;
    }

    a:hover {
        text-decoration: none;
    }

    h1, h3 {
        font-weight: bolder;
    }
</style>
{% endblock %}
{% block js %}
<script src='https://www.google.com/recaptcha/api.js'></script>
<script src="{% static 'js/create_article.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/summernote.min.js' %}"></script>
<script src="{% static 'js/summernote-ru-RU.min.js' %}"></script>
{% endblock %}
{% block menu %}
<a href="{% url 'index' %}" class="menu-page">Вернуться на сайт</a>
<a href="{% url 'specialists:account' %}" class="menu-page">Личный кабинет</a>
<a href="{% url 'authentication:edit_profile_page' %}" class="menu-page">Редактировать профиль</a>
<a href="{% url 'authentication:logout' %}" class="menu-page">Выйти</a>
{% endblock %}
{% block content %}
<h3 class="page-title">Редактирование материала</h3>
<div class="separator"></div>
<div class="create-article-form">
    <input type="text" class="med-input create-article-theme" placeholder="Тема" value="{{ article.theme }}">
    <input type="text" class="med-input create-article-title" placeholder="Название" value="{{ article.title }}">
    <textarea class="med-input create-article-text" placeholder="Текст статьи" style="display: none;">{{ article.text }}</textarea>
    <div class="summernote"></div>
</div>
<div class="separator"></div>
<h3 class="page-label">Прикреплённые файлы</h3>
<div class="create-article-files">
    {% if files_quantity <= 5 %}
        <div class="create-article-add-file">+</div>
    {% endif %}
    {% for file in article.get_files %}
    <div class="create-article-file-block">
        <input type="text" class="med-input create-article-file-name" placeholder="Подпись к файлу" id="name-pk{{ file.pk }}" value="{{ file.name }}">
        <span class="med-input create-article-file" id="file-pk{{ file.pk }}">{{ file.file.name|file_name }}</span>
        <div class="create-article-remove-file">+</div>
    </div>
    {% endfor %}
    <div class="create-article-file-block">
        <input type="text" class="med-input create-article-file-name" placeholder="Подпись к файлу" id="name-0">
        <input type="file" class="med-input create-article-file" id="file-0">
        <div class="create-article-remove-file">+</div>
    </div>
</div>
<div class="separator"></div>
{% csrf_token %}
<div class="create-article-recaptha-wrapper"><div class="form-group g-recaptcha" data-sitekey="6Lf_F2YoAAAAAAVQNp1zYPQk7S5cdxh7ylOkxGCU"></div></div>
<div class="create-article-notification faq-form-notification"></div>
<div class="med-button edit-article-submit">Сохранить</div>
<a href="{% url 'specialists:account' %}" class="consultation-read-link" style="display: block;">Назад</a>
<div class="faq-background">
    <div class="faq-form-block">
        <span class="faq-form-notification">Материал успешно отредактирован!</span>
        <a href="{% url 'specialists:account' %}" class="med-button" style="margin-top: 10px;">Ок</a>
    </div>
</div>
{% endblock %}