MedProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from MedProject import settings
import main.views as main
from django.views.i18n import JavaScriptCatalog
from main.decorators import check_recaptcha
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin_tools/', include('admin_tools.urls')),

    path('', main.index, name='index'),
    path('reviews/', main.ReviewsList.as_view(), name='reviews'),
    path('reviews/<int:page>/', main.ReviewsList.as_view(), name='reviews_page'),
    path('create_review/', check_recaptcha(main.create_review), name='create_review'),
    path('faq/', main.FaqView.as_view(), name='faq'),
    path('faq/<int:page>/', main.FaqView.as_view(), name='faq_page'),
    path('create_question/', check_recaptcha(main.create_question), name='create_question'),
    path('consultation/', main.consultation, name='consultation'),
    path('create_application/', check_recaptcha(main.create_application), name='create_application'),
    path('geography/', main.geography, name='geography'),
    path('news/', main.NewsList.as_view(), name='news'),
    path('news/<int:page>/', main.NewsList.as_view(), name='news_page'),
    path('single_news/<int:pk>/', main.single_news, name='single_news'),

    path('custom/', include('custom.urls', namespace='custom')),
    path('authentication/', include('authentication.urls', namespace='authentication')),
    path('specialists/', include('specialists.urls', namespace='specialists')),

    path('editor/', include('django_summernote.urls')),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('password-reset/', PasswordResetView.as_view(template_name='authentication/password_reset.html'), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/',PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path
import authentication.views as auth
from main.decorators import check_recaptcha

app_name = 'authentication'

urlpatterns = [
    path('login/', auth.login, name='login'),
    path('logout/', auth.logout, name='logout'),
    path('register/', auth.register, name='register'),
    path('edit_profile_page/', auth.edit_profile_page, name='edit_profile_page'),
    path('edit_profile/', check_recaptcha(auth.edit_profile), name='edit_profile'),
    path('edit_foas/', check_recaptcha(auth.edit_foas), name='edit_foas'),
    path('delete_application/', auth.delete_application, name='delete_application'),
    path('change_password/', auth.change_password, name='change_password'),
    path('verify/<str:email>/<str:key>/', auth.verify, name='verify'),
    path('send_verify_email_page/', auth.send_verify_email_page, name='send_verify_email_page'),
    path('renew_verification_key/', auth.renew_verification_key, name='renew_verification_key'),
    path('send_application/', auth.send_application, name='send_application'),
    path('rules/', auth.rules, name='rules'),
]

custom/urls.py
from django.urls import path
import custom.views as custom

app_name = 'custom'

urlpatterns = [
    path('add_album_page/', custom.add_album_page, name='add_album_page'),
    path('add_album/', custom.add_album, name='add_album'),
    path('add_fileset_page/', custom.add_fileset_page, name='add_fileset_page'),
    path('add_fileset/', custom.add_fileset, name='add_fileset'),
    path('<str:url>/', custom.constructor, name='constructor'),
]

specialists/urls.py
from django.urls import path
import specialists.views as spec
from main.decorators import check_recaptcha

app_name = 'specialists'

urlpatterns = [
    path('account/', spec.account, name='account'),
    path('create_article_page/', spec.create_article_page, name='create_article_page'),
    path('create_article/', check_recaptcha(spec.create_article), name='create_article'),
    path('edit_article_page/<int:pk>/', spec.edit_article_page, name='edit_article_page'),
    path('edit_article/', check_recaptcha(spec.edit_article), name='edit_article'),
    path('delete_article/', spec.delete_article, name='delete_article'),
    path('delete_application/', spec.delete_application, name='delete_application'),
    path('hide_article/', spec.hide_article, name='hide_article'),
    path('profile/<int:pk>/', spec.profile, name='profile'),
    path('article/<int:pk>/', spec.article, name='article'),
    path('specialists/', spec.SpecialistsList.as_view(), name='specialists'),
    path('specialists/<int:page>/', spec.SpecialistsList.as_view(), name='specialists_page'),
]

main/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic import ListView
from custom.models import Page, Section
from .models import QuestionAnswer, Review, MainSliderImage, Application, Place, News, SiteContent, Banner, IndexLink
from django.conf import settings
from django.core.mail import send_mail
from MedProject.settings import BASE_URL


def index(request):
    colors = ['#4F55DA', '#F06445', '#E8C444', '#B8D935', '#4FC9DA']
    questions_set = QuestionAnswer.objects.filter(approved=True).order_by('-id')[0:5:1]
    questions_list = []

    for i, review in enumerate(questions_set):
        questions_list.append((review, colors[i % 5]))

    slides = [{'image': i.image.url,
               'link': i.link if i.link is not None else ''} for i in MainSliderImage.objects.all().order_by('order')]
    banners = [{'image': i.image.url, 'link': i.link, 'name': i.name} for i in Banner.objects.all().order_by('-pk')]
    links = [{'image': i.image.url if bool(i.image) else '', 'link': i.link, 'name': i.name} for i in IndexLink.objects.all().order_by('-pk')]

    links_display = True
    try:
        links_display = int(SiteContent.objects.get(name='index_links_display').content)
    except ValueError:
        pass

    context = {
        'title': 'Главная',
        'menu_sections': Section.objects.all().order_by('order'),
        'account_section_id': int(SiteContent.objects.get(name='account_section_id').content),
        'menu_pages': Page.objects.filter(section=None),
        'header_content': [SiteContent.objects.get(name='email').content,
                                     SiteContent.objects.get(name='phone').content,
                                     SiteContent.objects.get(name='phone').content.translate(
                                         str.maketrans({' ': '', '-': '', '(': '', ')': ''}))],
        'slides': slides,
        'banners': banners,
        'news': News.objects.all().order_by('order', '-pk')[0:6:1],
        # 'questions': questions_list
        'text': SiteContent.objects.get(name='index_text').content,
        'links': links,
        'links_display': links_display,
        'links_label': SiteContent.objects.get(name='index_links_label').content,
    }

    return render(request, 'main/index.html', context)


class ReviewsList(ListView):
    model = Review
    template_name = 'main/reviews.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Отзывы'
        context['menu_sections'] = Section.objects.all().order_by('order')
        context['account_section_id'] = int(SiteContent.objects.get(name='account_section_id').content)
        context['menu_pages'] = Page.objects.filter(section=None)
        context['header_content'] = [SiteContent.objects.get(name='email').content,
                                     SiteContent.objects.get(name='phone').content,
                                     SiteContent.objects.get(name='phone').content.translate(
                                         str.maketrans({' ': '', '-': '', '(': '', ')': ''}))]

        return context

    def get_queryset(self):
        colors = ['#4F55DA', '#F06445', '#E8C444', '#B8D935', '#4FC9DA']
        reviews_set = Review.objects.filter(approved=True).order_by('-pk')
        reviews_list = []

        for i, review in enumerate(reviews_set):
            reviews_list.append((review, colors[i % 5]))
        return reviews_list


def create_review(request):

    name = request.POST.get('name')
    text = request.POST.get('text')

    if request.recaptcha_is_valid:
        if name and text:
            try:
                Review.objects.create(text=text, name=name)
                return JsonResponse({'result': 'ok'})
            except:
                pass
    else:
        return JsonResponse({'result': 'captcha'})

    return JsonResponse({'result': 'failed'})


class FaqView(ListView):
    model = QuestionAnswer
    template_name = 'main/faq.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Вопрос - ответ'
        context['menu_sections'] = Section.objects.all().order_by('order')
        context['account_section_id'] = int(SiteContent.objects.get(name='account_section_id').content)
        context['menu_pages'] = Page.objects.filter(section=None)
        context['header_content'] = [SiteContent.objects.get(name='email').content,
                                     SiteContent.objects.get(name='phone').content,
                                     SiteContent.objects.get(name='phone').content.translate(
                                         str.maketrans({' ': '', '-': '', '(': '', ')': ''}))]

        return context

    def get_queryset(self):
        colors = ['#4F55DA', '#F06445', '#E8C444', '#B8D935', '#4FC9DA']
        questions_set = QuestionAnswer.objects.filter(approved=True).order_by('-pk')
        questions_list = []

        for i, question in enumerate(questions_set):
            questions_list.append((question, colors[i % 5]))
        return questions_list


def create_question(request):

    name = request.POST.get('name')
    question = request.POST.get('question')

    if request.recaptcha_is_valid:
        if name and question:
            try:
                QuestionAnswer.objects.create(question=question, name=name)
                return JsonResponse({'result': 'ok'})
            except:
                pass
    else:
        return JsonResponse({'result': 'captcha'})

    return JsonResponse({'result': 'failed'})


def consultation(request):

    context = {
        'title': 'Интерактивная консультация',
        'menu_sections': Section.objects.all().order_by('order'),
        'account_section_id': int(SiteContent.objects.get(name='account_section_id').content),
        'menu_pages': Page.objects.filter(section=None),
        'rules_url': SiteContent.objects.get(name='rules_url').content,
        'header_content': [SiteContent.objects.get(name='email').content,
                                     SiteContent.objects.get(name='phone').content,
                                     SiteContent.objects.get(name='phone').content.translate(
                                         str.maketrans({' ': '', '-': '', '(': '', ')': ''}))],
        'text': SiteContent.objects.get(name='application_text').content
    }

    return render(request, 'main/consultation.html', context)


def create_application(request):

    first_name = request.POST.get('name')
    last_name = request.POST.get('surname')
    patronymic = request.POST.get('patronymic')
    email = request.POST.get('email')
    phone_number = request.POST.get('phone_number')
    text = request.POST.get('question')
    address = request.POST.get('address')

    if request.recaptcha_is_valid:
        if first_name and last_name and patronymic and email and phone_number and text:
            try:
                app = Application.objects.create(text=text, first_name=first_name, last_name=last_name, patronymic=patronymic,
                                                 email=email, phone_number=phone_number, address=address)
                if not BASE_URL == 'http://127.0.0.1:8000':
                    message = f'Email: {email}\nСсылка на заявку: {BASE_URL}/admin/main/application/{app.pk}/'
                    send_mail(
                        'Новая заявка на консультацию',
                        message,
                        settings.EMAIL_HOST_USER,
                        [SiteContent.objects.get(name='notification_email').content],
                        fail_silently=False
                    )

                    message = f'{SiteContent.objects.get(name="email_application_message").content}'
                    send_mail(
                        'Ваша заявка на консультацию успешно отправлена',
                        message,
                        settings.EMAIL_HOST_USER,
                        [email],
                        fail_silently=False
                    )

                return JsonResponse({'result': 'ok'})
            except:
                pass
    else:
        return JsonResponse({'result': 'captcha'})

    return JsonResponse({'result': 'failed'})


def geography(request):

    context = {
        'title': 'География ранней помощи',
        'menu_sections': Section.objects.all().order_by('order'),
        'account_section_id': int(SiteContent.objects.get(name='account_section_id').content),
        'menu_pages': Page.objects.filter(section=None),
        'header_content': [SiteContent.objects.get(name='email').content,
                                     SiteContent.objects.get(name='phone').content,
                                     SiteContent.objects.get(name='phone').content.translate(
                                         str.maketrans({' ': '', '-': '', '(': '', ')': ''}))],
        'places': Place.objects.all().order_by('order')
    }

    return render(request, 'main/geography.html', context)


class NewsList(ListView):
    model = News
    template_name = 'main/news.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Новости'
        context['menu_sections'] = Section.objects.all().order_by('order')
        context['account_section_id'] = int(SiteContent.objects.get(name='account_section_id').content)
        context['menu_pages'] = Page.objects.filter(section=None)
        context['header_content'] = [SiteContent.objects.get(name='email').content,
                                     SiteContent.objects.get(name='phone').content,
                                     SiteContent.objects.get(name='phone').content.translate(
                                         str.maketrans({' ': '', '-': '', '(': '', ')': ''}))]

        return context

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{{ title }}{% endblock %}</title>
        {% block css %}
        {% endblock %}
        <link rel="stylesheet" href="{% static 'css/style.css'%}">
        <link type="image/x-icon" href="/static/img/logo.png" rel="shortcut icon" id="head_icon">
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/base.js' %}"></script>
        <script async src="https://cse.google.com/cse.js?cx=92e3da7a8ab554250"></script>
        {% block js %}
        {% endblock %}
    </head>
    <body>
        <div class="base-background"></div>
        <div class="base-sidebar">
            <a href="{% url 'index' %}" class="base-logo-block">
                <img src="{% static 'img/logo.png' %}" alt="logo" class="base-logo">
            </a>
            <div class="base-search-block">
                <!-- <input type="text" class="base-search" placeholder="Поиск"> -->
                <div class="gcse-search"></div>
            </div>
            <div class="base-menu">
                {% block menu %}
                    <a href="{% url 'index' %}" class="menu-page{% if 'index' in request.resolver_match.url_name %} active{% endif %}">Главная</a>
                    {% for section in menu_sections %}
                        <div class="menu-section-block{% if current_page and current_page.section.pk == section.pk %} active{% endif %}" id="menu-section-{{ section.pk }}">
                            <span class="menu-section">{{ section.name }}
                            <img src="{% static 'img/menu-arrow.svg' %}" alt=">" class="menu-section-arrow"{% if current_page and current_page.section.pk == section.pk %} style="transform: rotate(-90deg);"{% endif %}>
                        </div>
                        <div class="menu-section-dropdown" id="menu-dropdown-{{ section.pk }}"{% if current_page and current_page.section.pk == section.pk %} style="display: flex; height: auto;"{% endif %}>
                            {% for page in section.get_pages %}
                                {% if page.approved or user.is_staff %}
                                    <a href="{% url 'custom:constructor' url=page.url %}" class="menu-section-page{% if page.url == request.resolver_match.kwargs.url %} active{% endif %}">
                                        {{ page.title }}<div class="menu-section-page-circle"></div>
                                    </a>
                                {% endif %}
                            {% endfor %}
                            {% if section.pk == account_section_id %}
                                {% if user.is_superuser %}
                                    <a href="{% url 'admin:index' %}" class="menu-section-page">Личный кабинет<div class="menu-section-page-circle"></div></a>
                                {% elif user.is_authenticated %}
                                    <a href="{% url 'specialists:account' %}" class="menu-section-page">Личный кабинет<div class="menu-section-page-circle"></div></a>
                                {% else %}
                                    <a href="{% url 'authentication:login' %}" class="menu-section-page{% if 'login' in request.resolver_match.namespace %} active{% endif %}">Личный кабинет<div class="menu-section-page-circle"></div></a>
                                {% endif %}
                            {% endif%}
                        </div>
                    {% endfor %}
                    {% for page in menu_pages %}
                        {% if page.approved or user.is_staff %}
                            <a href="{% url 'custom:constructor' url=page.url %}" class="menu-page{% if page.url == request.resolver_match.kwargs.url %} active{% endif %}">{{ page.title }}</a>
                        {% endif %}
                    {% endfor %}
                    <a href="{% url 'news' %}" class="menu-page{% if 'news' in request.resolver_match.url_name %} active{% endif %}">Новости</a>
                    <a href="{% url 'geography' %}" class="menu-page{% if 'geography' in request.resolver_match.url_name %} active{% endif %}">География ранней помощи </a>
                    <a href="{% url 'consultation' %}" class="menu-page{% if 'consultation' in request.resolver_match.url_name %} active{% endif %}">Интерактивная консультация</a>
                    <a href="{% url 'faq' %}" class="menu-page{% if 'faq' in request.resolver_match.url_name %} active{% endif %}">Вопрос - ответ</a>
                    <a href="{% url 'reviews' %}" class="menu-page{% if 'reviews' in request.resolver_match.url_name %} active{% endif %}">Отзывы</a>
                    <a href="{% url 'specialists:specialists' %}" class="menu-page{% if 'specialists' in request.resolver_match.url_name %} active{% endif %}">Специалисты ранней помощи</a>
                {% endblock %}
            </div>
        </div>
        <div class="base-container">
            <div class="poor-vision-block">
                <img src="{% static 'img/menu-arrow.svg' %}" alt="скрыть/показать" class="poor-vision-hide">
                <span class="poor-vision-settings">Настройки версии для слабовидящих</span>
                <div class="poor-vision-subblock">
                    <span>Шрифт:</span>
                    <div class="poor-vision-options">
                        <div class="poor-vision-option" id="font-off">100%</div>
                        <div class="poor-vision-option" id="font-150">150%</div>
                        <div class="poor-vision-option" id="font-200">200%</div>
                    </div>
                </div>
                <div class="poor-vision-subblock">
                    <span>Цвет:</span>
                    <div class="poor-vision-options">
                        <div class="poor-vision-option" id="bg-off"><span>Обычный</span></div>
                        <div class="poor-vision-option" id="bg-white"><span>H</span></div>
                        <div class="poor-vision-option" id="bg-black"><span>H</span></div>
                        <div class="poor-vision-option" id="bg-blue"><span>H</span></div>
                    </div>
                </div>
                <div class="poor-vision-subblock">
                    <span>Интервал:</span>
                    <div class="poor-vision-options">
                        <div class="poor-vision-option" id="ls-off">Обычный</div>
                        <div class="poor-vision-option" id="ls-medium">Средний</div>
                        <div class="poor-vision-option" id="ls-big">Большой</div>
                    </div>
                </div>
                <div class="poor-vision-subblock">
                    <span>Изображения:</span>
                    <div class="poor-vision-options">
                        <div class="poor-vision-option" id="images-off">Отключить</div>
                    </div>
                </div>
                <div class="poor-vision-subblock">
                    <span class="poor-vision-normal">Обычная версия</span>
                </div>
            </div>
            <div class="base-header">
                {% block header %}
                <div class="header-left-block">
                    <div class="header-menu-show">
                        <div class="header-menu-show-subblock"></div>
                        <div class="header-menu-show-subblock"></div>
                        <div class="header-menu-show-subblock"></div>
                    </div>
                    <a href="{% url 'index' %}" class="med-button">Главная</a>
                </div>
                <a href="{% url 'index' %}" class="header-title-block">
                    <h1>Региональный ресурсно - методический центр ранней помощи детям и их семьям в Иркутской области</h1>
                </a>
                <div class="header-right-block">
                    <div class="header-contacts-block">
                        <a href="mailto:{{ header_content.0 }}">{{ header_content.0 }}</a>
                        <a href="tel:{{ header_content.2 }}">{{ header_content.1 }}</a>
                    </div>
                    <a href="mailto:{{ header_content.0 }}" class="header-img-block">
                        <img src="{% static 'img/email.png' %}" class="header-img">
                    </a>
                    <a href="tel:{{ header_content.2 }}" class="header-img-block">
                        <img src="{% static 'img/phone.png' %}" class="header-img">
                    </a>
                    <div class="header-poor-vision">
                        <span>Версия для слабовидящих</span>
                        <img src="{% static 'img/poor_vision.png' %}" class="header-poor-vision-img">
                    </div>
                </div>
                {% endblock %}
            </div>
            <div class="base-content">
                {% block content %}
                {% endblock %}
            </div>
            <div class="base-footer">
                {% block footer %}
                {% endblock %}
            </div>
        </div>
        <!-- Yandex.Metrika counter -->
<script type="text/javascript" >
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();
   for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
   k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(96571931, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/96571931" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
    </body>
</html>

main/templates/main/consultation.html
{% extends 'main/base.html' %}
{% load static %}
{% block js %}
<script src='https://www.google.com/recaptcha/api.js'></script>
<script src="{% static 'js/consultation.js' %}"></script>
{% endblock %}
{% block content %}
<h3 class="page-title">Интерактивная консультация</h3>
<div class="separator"></div>
<p class="consultation-intro">{{ text|safe }}</p>
<div class="consultation-form">
    {% csrf_token %}
    <div class="consultation-form-subblock">
        <input type="text" class="med-input consultation-name" placeholder="Имя">
        <input type="text" class="med-input consultation-surname" placeholder="Фамилия">
        <input type="text" class="med-input consultation-patronymic" placeholder="Отчество">
        <input type="text" class="med-input consultation-phone-number" placeholder="Номер телефона">
        <input type="email" class="med-input consultation-email" placeholder="Адрес электронной почты">
    </div>
    <div class="consultation-form-subblock">
        <input type="text" class="med-input consultation-address" placeholder="Адрес">
        <textarea class="med-input consultation-question" placeholder="Ваш вопрос"></textarea>
    </div>
    <div class="consultation-form-subblock">
        <div class="form-group g-recaptcha" data-sitekey="6Lf_F2YoAAAAAAVQNp1zYPQk7S5cdxh7ylOkxGCU"></div>
        <div class="consultation-checkbox-block"><input type="checkbox" class="consultation-checkbox"><span>Даю согласие на обработку персональных данных</span></div>
        <a {% if rules_url %}href="{% url 'custom:constructor' url=rules_url %}"{% else %}href="#"{% endif %} class="consultation-read-link">Правила обработки персональных данных</a>
        <span class="med-button consultation-submit">Отправить</span>
    </div>
</div>
<div class="faq-background">
    <div class="faq-form-block">
        <span class="faq-form-notification"></span>
    </div>
</div>
{% endblock %}

main/templates/main/faq.html
{% extends 'main/base.html' %}
{% load static %}
{% block js %}
<script src='https://www.google.com/recaptcha/api.js'></script>
<script src="{% static 'js/text-adjust.js' %}"></script>
<script src="{% static 'js/faq.js' %}"></script>
{% endblock %}
{% block content %}
<div class="faq-header">
    <h3 class="page-title">Вопрос - Ответ</h3>
    <h3 class="faq-ask-question med-button">Задайте свой вопрос</h3>
</div>
<div class="separator"></div>
{% for question in object_list %}
<div class="index-faq-block faq-faq-block">
    <div class="index-faq-color-block" style="background-color: {{ question.1 }};"></div>
    <span class="faq-asking-name">{{ question.0.name }}</span>
    <span class="text-to-adjust faq-question" id="question-{{ question.0.pk }}">{{ question.0.question }}</span>
    <p class="text-to-adjust index-answer" id="answer-{{ question.0.pk }}">{{ question.0.answer }}</p>
</div>
{% endfor %}
<div class="paginator-menu">
    {% if page_obj.has_previous %}
        <a href="{% url 'faq_page' page_obj.previous_page_number %}" class="paginator-previous">
            ↼&nbsp
        </a>
    {% else %}
        &nbsp&nbsp&nbsp
    {% endif %}
      <p>
          {% if page_obj %}
            {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
          {% endif %}
      </p>
    {% if page_obj.has_next %}
        <a href="{% url 'faq_page' page_obj.next_page_number %}" class="paginator-next">
            &nbsp⇁
        </a>
    {% else %}
        &nbsp&nbsp&nbsp
    {% endif %}
</div>
{% if not object_list %}
    <div class="faq-form-notification">На данный момент тут ничего нет</div>
{% endif %}
<div class="faq-background">
    <div class="faq-form-block">
        {% csrf_token %}
        <span class="faq-form-notification"></span>
        <input type="text" class="med-input faq-name-input" placeholder="Ваше имя">
        <textarea class="med-input faq-question-input" placeholder="Ваш вопрос"></textarea>
        <div class="form-group g-recaptcha" data-sitekey="6Lf_F2YoAAAAAAVQNp1zYPQk7S5cdxh7ylOkxGCU"></div>
        <span class="med-button faq-form-submit">Отправить</span>
    </div>
</div>
{% endblock %}

main/templates/main/geography.html
{% extends 'main/base.html' %}
{% load static %}
{% block js %}
<script src="{% static 'js/text-adjust.js' %}"></script>
<script src="{% static 'js/geography.js' %}"></script>
{% endblock %}
{% block content %}
<div class="geo-content">
    <div class="geo-names">
        <div class="geo-separator"></div>
        {% for place in places %}
        <div class="geo-name-block" id="name-{{ place.pk }}">
            <div class="geo-name">{{ place.name }}</div>
            {% if place.text %}
                <div class="geo-text text-to-adjust" id="text-{{ place.pk }}">{{ place.text }}</div>
            {% endif %}
            {% if place.get_institutions %}
                <div class="geo-info-block" id="info-{{ place.pk }}">
                    {% for i in place.get_institutions %}
                        <div>
                            <div class="geo-info">{{ i.name }}</div>
                            <div class="geo-info">{{ i.address }}</div>
                            <div class="geo-info">{{ i.phone_number }}</div>
                            {% if i.link %}
                                <a href="{{ i.link }}" class="geo-info-link" target="_blank">Перейти на сайт</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="geo-separator"></div>
        {% endfor %}
    </div>
    <div class="geo-places">
        {% for place in places %}
        <iframe src="{{ place.src }}" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" class="geo-place" id="src-{{ place.pk }}"></iframe>
        {% endfor %}
    </div>
</div>
{% if not places %}
    <div class="faq-form-notification">На данный момент тут ничего нет</div>
{% endif %}
{% endblock %}

main/templates/main/single_news.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<h3 class="page-title single-news-title">{{ current_news.title }}</h3>
<span class="index-news-date">{{ current_news.date }}</span>
<div class="single-news-img-block">
    <img src="/media/{{ current_news.image }}" alt="image" class="index-news-img">
</div>
<div class="news-news-content">{{ current_news.content|safe }}</div>
{% endblock %}